/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2018-05-03 07:16:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"no-js fixed-layout\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("\t<title>Admin Index Page | SpiderSystem</title>\n");
      out.write("\t<!-- 以下代码告诉IE浏览器，IE8/9及以后的版本都会以最高版本IE来渲染页面 -->\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\n");
      out.write("  <meta name=\"description\" content=\"the admin_index of SpiderSystem\">\n");
      out.write("  <meta name=\"keywords\" content=\"index SpiderSystem\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<meta name=\"renderer\" content=\"webkit\">\n");
      out.write("\t<!-- 以下代码取消第三方转码 -->\n");
      out.write("\t<meta name=\"Cache-Control\" content=\"no-siteapp\">\n");
      out.write("\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\"\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/i/favicon.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/i/app-icon72x72@2x.png\">\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/css/amazeui.min.css\">\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("  \thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/css/admin.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!--[if lte IE 9]>\n");
      out.write("  <p class=\"browsehappy\">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href=\"http://browsehappy.com/\" target=\"_blank\">升级浏览器</a>\n");
      out.write("    以获得更好的体验！</p>\n");
      out.write("  <![endif]-->\n");
      out.write("  \n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "included_header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"am-cf admin-main\">\n");
      out.write("    <!-- sidebar start-->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "included_sidebar.jsp", out, false);
      out.write("\n");
      out.write("    <!-- siderbar end -->\n");
      out.write("\n");
      out.write("    <!-- content start -->\n");
      out.write("  <div class=\"admin-content\">\n");
      out.write("    <div class=\"admin-content-body\">\n");
      out.write("      <div class=\"am-cf am-padding am-padding-bottom-0\">\n");
      out.write("        <div class=\"am-fl am-cf\"><strong class=\"am-text-primary am-text-lg\">个人资料</strong> / <small>Personal information</small></div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <hr/>\n");
      out.write("\n");
      out.write("      <div class=\"am-g\">\n");
      out.write("        <div class=\"am-u-sm-12 am-u-md-4 am-u-md-push-8\">\n");
      out.write("      \t<div class=\"am-panel am-panel-default\">\n");
      out.write("            <div class=\"am-panel-bd\">\n");
      out.write("              <div class=\"user-info\">\n");
      out.write("                <p>等级信息</p>\n");
      out.write("                <div class=\"am-progress am-progress-sm\">\n");
      out.write("                  <div class=\"am-progress-bar\" style=\"width: 60%\"></div>\n");
      out.write("                </div>\n");
      out.write("                <p class=\"user-info-order\">当前等级：<strong>LV8</strong> 活跃天数：<strong>587</strong> 距离下一级别：<strong>160</strong></p>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"user-info\">\n");
      out.write("                <p>信用信息</p>\n");
      out.write("                <div class=\"am-progress am-progress-sm\">\n");
      out.write("                  <div class=\"am-progress-bar am-progress-bar-success\" style=\"width: 80%\"></div>\n");
      out.write("                </div>\n");
      out.write("                <p class=\"user-info-order\">信用等级：正常当前 信用积分：<strong>80</strong></p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"am-u-sm-12 am-u-md-8 am-u-md-pull-4\">\n");
      out.write("          <form class=\"am-form am-form-horizontal\">\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-name\" class=\"am-u-sm-3 am-form-label\">姓名 / Name</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <input type=\"text\" id=\"user-name\">\n");
      out.write("                <small>输入你的名字，让我们记住你。</small>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-email\" class=\"am-u-sm-3 am-form-label\">电子邮件 / Email</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <input type=\"email\" id=\"user-email\">\n");
      out.write("                <small>邮箱你懂得...</small>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-phone\" class=\"am-u-sm-3 am-form-label\">电话 / Telephone</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <input type=\"tel\" id=\"user-phone\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-QQ\" class=\"am-u-sm-3 am-form-label\">QQ</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <input type=\"text\" id=\"user-QQ\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-weibo\" class=\"am-u-sm-3 am-form-label\">微博 / Twitter</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <input type=\"text\" id=\"user-weibo\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <label for=\"user-intro\" class=\"am-u-sm-3 am-form-label\">简介 / Intro</label>\n");
      out.write("              <div class=\"am-u-sm-9\">\n");
      out.write("                <textarea class=\"\" rows=\"5\" id=\"user-intro\"></textarea>\n");
      out.write("                <small>250字以内写出你的一生...</small>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <div class=\"am-u-sm-9 am-u-sm-push-3\">\n");
      out.write("                <button type=\"button\" class=\"am-btn am-btn-primary\" onclick=\"save()\">保存修改</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "included_footer.jsp", out, false);
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <!-- content end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"http://libs.baidu.com/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js\"></script>\n");
      out.write("  <script src=\"assets/js/amazeui.ie8polyfill.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!--[if (gte IE 9)|!(IE)]><!-->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery.min.js\"></script>\n");
      out.write("  <!--<![endif]-->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/js/amazeui.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/js/app.js\"></script>\n");
      out.write("\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  \tvar ori_name,ori_email,ori_phone,ori_QQ,ori_weibo,ori_intro;\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \t$(function(){\n");
      out.write("\t\t// alert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("\t\t// return;\n");
      out.write("  \t\t$.ajax({\n");
      out.write("             url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/show\",\n");
      out.write("             type: \"POST\",\n");
      out.write("             dataType: \"json\",\n");
      out.write("             data: {\n");
      out.write("               \"adminId\": \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("             },\n");
      out.write("             async: false,\n");
      out.write("             success: function(data) {\n");
      out.write("            \t if(data.result == \"success\"){\n");
      out.write("                \t // alert(\"操作成功\");\n");
      out.write("                \t ori_name = data.adminName;\n");
      out.write("                \t $(\"#user-name\").attr(\"value\",ori_name);\n");
      out.write("                \t ori_email = data.adminEmail;\n");
      out.write("                \t $(\"#user-email\").attr(\"value\",ori_email);\n");
      out.write("                \t ori_phone = data.adminTelephone;\n");
      out.write("                \t $(\"#user-phone\").attr(\"value\",ori_phone);\n");
      out.write("                \t ori_QQ = data.adminQq;\n");
      out.write("                \t $(\"#user-QQ\").attr(\"value\",ori_QQ);\n");
      out.write("                \t ori_weibo = data.adminTwitter;\n");
      out.write("                \t $(\"#user-weibo\").attr(\"value\",ori_weibo);\n");
      out.write("                \t ori_intro = data.adminIntro;\n");
      out.write("                \t $(\"#user-intro\").html(ori_intro);\n");
      out.write("                 }else{\n");
      out.write("                \t alert(\"数据读取失败\");\n");
      out.write("                 }\n");
      out.write("             },\n");
      out.write("             error: function() {\n");
      out.write("               alert(\"访问服务器失败，...请检查网络连接，如确实怀疑服务器问题请联系Zzy\");\n");
      out.write("             }\n");
      out.write("           });\n");
      out.write("\t});\n");
      out.write("  \t\n");
      out.write("  \tfunction save(){\n");
      out.write("  \t\tvar now_name = $(\"#user-name\").val(),\n");
      out.write("  \t\tnow_email = $(\"#user-email\").val(),\n");
      out.write("  \t\tnow_phone = $(\"#user-phone\").val(),\n");
      out.write("  \t\tnow_QQ = $(\"#user-QQ\").val(),\n");
      out.write("  \t\tnow_weibo = $(\"#user-weibo\").val(),\n");
      out.write("  \t\tnow_intro = $(\"#user-intro\").val();\n");
      out.write("  \t\t\n");
      out.write("  \t\t\n");
      out.write("  \t\tif(\n");
      out.write("  \t\t\tnow_name == ori_name &&\n");
      out.write("  \t\t\tnow_email == ori_email &&\n");
      out.write("  \t\t\tnow_phone == ori_phone &&\n");
      out.write("  \t\t\tnow_QQ == ori_QQ &&\n");
      out.write("  \t\t\tnow_weibo == ori_weibo &&\n");
      out.write("  \t\t\tnow_intro == ori_intro\n");
      out.write("  \t\t){\n");
      out.write("  \t\t\talert(\"并没有任何修改!!!\");\n");
      out.write("  \t\t\treturn;\n");
      out.write("  \t\t}\n");
      out.write("  \t\t\n");
      out.write("  \t\t$.ajax({\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/save\",\n");
      out.write("            type: \"POST\",\n");
      out.write("            dataType: \"json\",\n");
      out.write("            data: {\n");
      out.write("              \"adminId\": \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adminId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\n");
      out.write("              \"adminName\": now_name,\n");
      out.write("              \"adminEmail\": now_email,\n");
      out.write("              \"adminPhone\": now_phone,\n");
      out.write("              \"adminQq\": now_QQ,\n");
      out.write("              \"adminTwitter\": now_weibo,\n");
      out.write("              \"adminIntro\": now_intro\n");
      out.write("            },\n");
      out.write("            async: false,\n");
      out.write("            success: function(data) {\n");
      out.write("           \t if(data.result == \"success\"){\n");
      out.write("               \t alert(\"修改成功\");\n");
      out.write("               \t \n");
      out.write("                }else{\n");
      out.write("               \t alert(\"数据修改失败\");\n");
      out.write("                }\n");
      out.write("            },\n");
      out.write("            error: function() {\n");
      out.write("              alert(\"访问服务器失败，...请检查网络连接，如确实怀疑服务器问题请联系Zzy\");\n");
      out.write("            }\n");
      out.write("          });\n");
      out.write("  \t}\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
