/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2018-04-25 14:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class data_005fnews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1523365241000L));
    _jspx_dependants.put("jar:file:/Users/zzy/Desktop/这是毕设/SpiderSystem/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpiderSystem-Web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"no-js fixed-layout\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("\t<title>Admin Index Page | SpiderSystem</title>\n");
      out.write("\t<!-- 以下代码告诉IE浏览器，IE8/9及以后的版本都会以最高版本IE来渲染页面 -->\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\n");
      out.write("  <meta name=\"description\" content=\"the admin_index of SpiderSystem\">\n");
      out.write("  <meta name=\"keywords\" content=\"index SpiderSystem\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<meta name=\"renderer\" content=\"webkit\">\n");
      out.write("\t<!-- 以下代码取消第三方转码 -->\n");
      out.write("\t<meta name=\"Cache-Control\" content=\"no-siteapp\">\n");
      out.write("\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\"\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/i/favicon.png\">\n");
      out.write("  <link rel=\"apple-touch-icon-precomposed\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/i/app-icon72x72@2x.png\">\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/css/amazeui.min.css\">\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("  \thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/css/admin.css\">\n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("  \thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/pagination.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!--[if lte IE 9]>\n");
      out.write("  <p class=\"browsehappy\">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a href=\"http://browsehappy.com/\" target=\"_blank\">升级浏览器</a>\n");
      out.write("    以获得更好的体验！</p>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <header class=\"am-topbar am-topbar-inverse admin-header\">\n");
      out.write("    <div class=\"am-topbar-brand\">\n");
      out.write("      <strong>SpiderSystem</strong> <small>后台管理系统</small>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"am-collapse am-topbar-collapse\" id=\"topbar-collapse\">\n");
      out.write("      <ul class=\"am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list\">\n");
      out.write("        <li>\n");
      out.write("          <a href=\"#\">\n");
      out.write("            <span class=\"am-icon-envelope-o\"></span>收件箱\n");
      out.write("            <span class=\"am-badge am-badge-warning\">5</span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"am-dropdown\" data-am-dropdown>\n");
      out.write("          <a href=\"#\" class=\"am-dropdown-toggle\" data-am-dropdown-toggle>\n");
      out.write("            <span class=\"am-icon-users\"></span>管理员\n");
      out.write("            <span class=\"am-icon-caret-down\"></span>\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"am-dropdown-content\">\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <span class=\"am-icon-user\"></span>资料\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <span class=\"am-icon-cog\"></span>设置\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <span class=\"am-icon-power-off\"></span>退出\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"am-hide-sm-only\">\n");
      out.write("          <a href=\"#\" id=\"admin-fullscreen\">\n");
      out.write("            <span class=\"am-icon-arrows-alt\"></span>\n");
      out.write("            <span class=\"admin-fullText\">开启全屏</span>\n");
      out.write("          </a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <div class=\"am-cf admin-main\">\n");
      out.write("    <!-- sidebar start-->\n");
      out.write("    <div class=\"admin-sidebar am-offcanvas\" id=\"admin-offcanvas\">\n");
      out.write("      <div class=\"am-offcanvas-bar admin-offcanvas-bar\">\n");
      out.write("        <ul class=\"am-list admin-sidebar-list\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/index\">\n");
      out.write("              <span class=\"am-icon-home\"></span> 首 页\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <!--\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-nav'}\"><span class=\"am-icon-file\"></span> 页面模块 <span class=\"am-icon-angle-right am-fr am-margin-right\"></span></a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-nav\">\n");
      out.write("              <li><a href=\"admin-user.html\" class=\"am-cf\"><span class=\"am-icon-check\"></span> 个人资料<span class=\"am-icon-star am-fr am-margin-right admin-icon-yellow\"></span></a></li>\n");
      out.write("              <li><a href=\"admin-help.html\"><span class=\"am-icon-puzzle-piece\"></span> 帮助页</a></li>\n");
      out.write("              <li><a href=\"admin-gallery.html\"><span class=\"am-icon-th\"></span> 相册页面<span class=\"am-badge am-badge-secondary am-margin-right am-fr\">24</span></a></li>\n");
      out.write("              <li><a href=\"admin-log.html\"><span class=\"am-icon-calendar\"></span> 系统日志</a></li>\n");
      out.write("              <li><a href=\"admin-404.html\"><span class=\"am-icon-bug\"></span> 404</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          -->\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-spider'}\">\n");
      out.write("              <span class=\"am-icon-bug\"></span> 爬虫管理\n");
      out.write("              <span class=\"am-icon-angle-right am-fr am-margin-right\"></span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-spider\">\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/spider/check\" class=\"am-cf\">\n");
      out.write("                  <span class=\"am-icon-bug\"></span> 系统级爬虫\n");
      out.write("                  <span class=\"am-icon-star am-fr am-margin-right admin-icon-yellow\"></span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                  <span class=\"am-icon-bug\"></span> 用户级爬虫</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-data'}\">\n");
      out.write("              <span class=\"am-icon-table\"></span> 数据库\n");
      out.write("              <span class=\"am-icon-angle-right am-fr am-margin-right\"></span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-data\">\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/show\">\n");
      out.write("                  <span class=\"am-icon-pencil-square-o\"></span> 公告表\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/show\">\n");
      out.write("                  <span class=\"am-icon-pencil-square-o\"></span> 新闻表\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <div class=\"am-panel am-panel-default admin-sidebar-panel\">\n");
      out.write("          <div class=\"am-panel-bd\">\n");
      out.write("            <p>\n");
      out.write("              <span class=\"am-icon-bookmark\"></span> 公 告\n");
      out.write("            </p>\n");
      out.write("            <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.getText()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"am-panel am-panel-default admin-sidebar-panel\">\n");
      out.write("          <div class=\"am-panel-bd\">\n");
      out.write("            <p>\n");
      out.write("              <span class=\"am-icon-tag\"></span>SpiderSystem\n");
      out.write("            </p>\n");
      out.write("            <p>Welcome to the SpiderSystem !</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <ul class=\"am-list admin-sidebar-list\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"am-icon-sign-out\"></span> 注 销\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- siderbar end -->\n");
      out.write("\n");
      out.write("    <!-- content start -->\n");
      out.write("    <div class=\"admin-content\">\n");
      out.write("      <div class=\"admin-content-body\">\n");
      out.write("        <div class=\"am-cf am-padding am-padding-bottom-0\">\n");
      out.write("          <div class=\"am-fl am-cf\"><strong class=\"am-text-primary am-text-lg\">表格</strong> / <small>Table</small></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <hr>\n");
      out.write("        <!--\n");
      out.write("        <div class=\"am-g\">\n");
      out.write("          <div class=\"am-u-sm-12 am-u-md-6\">\n");
      out.write("            <div class=\"am-btn-toolbar\">\n");
      out.write("              <div class=\"am-btn-group am-btn-group-xs\">\n");
      out.write("                <button type=\"button\" class=\"am-btn am-btn-default\"><span class=\"am-icon-plus\"></span> 新增</button>\n");
      out.write("                <button type=\"button\" class=\"am-btn am-btn-default\"><span class=\"am-icon-save\"></span> 保存</button>\n");
      out.write("                <button type=\"button\" class=\"am-btn am-btn-default\"><span class=\"am-icon-archive\"></span> 审核</button>\n");
      out.write("                <button type=\"button\" class=\"am-btn am-btn-default\"><span class=\"am-icon-trash-o\"></span> 删除</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"am-u-sm-12 am-u-md-3\">\n");
      out.write("            <div class=\"am-form-group\">\n");
      out.write("              <select data-am-selected=\"{btnSize: 'sm'}\">\n");
      out.write("                <option value=\"option1\">所有类别</option>\n");
      out.write("                <option value=\"option2\">IT业界</option>\n");
      out.write("                <option value=\"option3\">数码产品</option>\n");
      out.write("                <option value=\"option3\">笔记本电脑</option>\n");
      out.write("                <option value=\"option3\">平板电脑</option>\n");
      out.write("                <option value=\"option3\">只能手机</option>\n");
      out.write("                <option value=\"option3\">超极本</option>\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"am-u-sm-12 am-u-md-3\">\n");
      out.write("            <div class=\"am-input-group am-input-group-sm\">\n");
      out.write("              <input type=\"text\" class=\"am-form-field\">\n");
      out.write("            <span class=\"am-input-group-btn\">\n");
      out.write("              <button class=\"am-btn am-btn-default\" type=\"button\">搜索</button>\n");
      out.write("            </span>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("      -->\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("        <div class=\"am-g\">\n");
      out.write("          <div class=\"am-u-sm-12\">\n");
      out.write("            <form class=\"am-form\">\n");
      out.write("              <table class=\"am-table am-table-striped am-table-hover table-main\">\n");
      out.write("                <thead>\n");
      out.write("                <tr>\n");
      out.write("                  <!--\n");
      out.write("                  <th class=\"table-check\">\n");
      out.write("                    <input type=\"checkbox\" />\n");
      out.write("                  </th>\n");
      out.write("                -->\n");
      out.write("                  <th class=\"table-id\">\n");
      out.write("                    id\n");
      out.write("                  </th>\n");
      out.write("                  <th class=\"table-title\">\n");
      out.write("                    title\n");
      out.write("                  </th>\n");
      out.write("                  <!--\n");
      out.write("                  <th class=\"table-content\">\n");
      out.write("                    content\n");
      out.write("                  </th>\n");
      out.write("                -->\n");
      out.write("                  <th class=\"table-time\">\n");
      out.write("                    date\n");
      out.write("                  </th>\n");
      out.write("                  <th class=\"table-url\">\n");
      out.write("                    url\n");
      out.write("                  </th>\n");
      out.write("                  <th class=\"table-set\">\n");
      out.write("                    操作\n");
      out.write("                  </th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("              </table>\n");
      out.write("              \n");
      out.write("              <div class=\"am-popup\" id=\"my-popup\">\n");
      out.write("  \t\t\t\t<div class=\"am-popup-inner\">\n");
      out.write("    \t\t\t\t<div class=\"am-popup-hd\">\n");
      out.write("      \t\t\t\t\t<h4 id=\"pop-title\" class=\"am-popup-title\">...</h4>\n");
      out.write("      \t\t\t\t\t<span data-am-modal-close class=\"am-close\">&times;</span>\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("    \t\t\t\t<div id=\"pop-content\" class=\"am-popup-bd\">\n");
      out.write("      \t\t\t\t\t\n");
      out.write("    \t\t\t\t</div>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("              \n");
      out.write("              <div id=\"pager\">\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      <footer class=\"admin-content-footer\">\n");
      out.write("        <hr>\n");
      out.write("        <p class=\"am-padding-left\">@ 2018 All Rights Reserved Zzy.</p>\n");
      out.write("      </footer>\n");
      out.write("    </div>\n");
      out.write("    <!-- content end-->\n");
      out.write("\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!--[if lt IE 9]>\n");
      out.write("  <script src=\"http://libs.baidu.com/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js\"></script>\n");
      out.write("  <script src=\"assets/js/amazeui.ie8polyfill.min.js\"></script>\n");
      out.write("  <![endif]-->\n");
      out.write("\n");
      out.write("  <!--[if (gte IE 9)|!(IE)]><!-->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery.pagination.js\"></script>\n");
      out.write("  <!--<![endif]-->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/js/amazeui.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/amazeui_assets/js/app.js\"></script>\n");
      out.write("\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("     //初始化分页组件\n");
      out.write("     var count=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news_count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("     var size=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news_size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("     var pageNO=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news_pageNO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("     $(\"#pager\").pagination(count, {\n");
      out.write("        items_per_page:size,\n");
      out.write("         current_page:pageNO-1,\n");
      out.write("         next_text:\"下一页\",\n");
      out.write("         prev_text:\"上一页\",\n");
      out.write("         num_edge_entries:2,\n");
      out.write("         load_first_page:false,\n");
      out.write("        callback:handlePaginationClick\n");
      out.write("      });\n");
      out.write("\n");
      out.write("     //回调方法\n");
      out.write("     function handlePaginationClick(new_page_index, pagination_container){\n");
      out.write("         location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/show?pageNO=\"+(new_page_index+1);\n");
      out.write("     }\n");
      out.write("     \n");
      out.write("     function news_select(newsId){\n");
      out.write("    \t // alert(newsId);\n");
      out.write("    \t alert(\"please wait for a short time...\")\n");
      out.write("    \t $.ajax({\n");
      out.write("             url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/select\",\n");
      out.write("             type: \"POST\",\n");
      out.write("             dataType: \"json\",\n");
      out.write("             contentType: \"application/x-www-form-urlencoded; charset=utf-8\", \n");
      out.write("             data: {\n");
      out.write("               \"newsId\": newsId\n");
      out.write("             },\n");
      out.write("             async: false,\n");
      out.write("             success: function(data) {\n");
      out.write("            \t if(data.result == \"success\"){\n");
      out.write("                \t // alert(\"操作成功\");\n");
      out.write("                \t $(\"#pop-title\").html(data.title);\n");
      out.write("                \t $(\"#pop-content\").html(data.content);\n");
      out.write("                \t $(\"#my-popup\").modal();\n");
      out.write("                 }else{\n");
      out.write("                \t alert(\"数据库操作失败\");\n");
      out.write("                 }\n");
      out.write("             },\n");
      out.write("             error: function() {\n");
      out.write("               alert(\"查询失败，...请检查网络连接，如确实怀疑服务器问题请联系Zzy\");\n");
      out.write("             }\n");
      out.write("           });\n");
      out.write("     }\n");
      out.write("     \n");
      out.write("     function news_del(newsId){\n");
      out.write("    \t $.ajax({\n");
      out.write("             url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/del\",\n");
      out.write("             type: \"POST\",\n");
      out.write("             dataType: \"json\",\n");
      out.write("             data: {\n");
      out.write("               \"newsId\": newsId\n");
      out.write("             },\n");
      out.write("             async: false,\n");
      out.write("             success: function(data) {\n");
      out.write("            \t if(data.result == \"success\"){\n");
      out.write("                \t alert(\"操作成功\");\n");
      out.write("                 }else{\n");
      out.write("                \t alert(\"数据库操作失败\");\n");
      out.write("                 }\n");
      out.write("             },\n");
      out.write("             error: function() {\n");
      out.write("               alert(\"删除失败，...请检查网络连接，如确实怀疑服务器问题请联系Zzy\");\n");
      out.write("             }\n");
      out.write("           });\n");
      out.write("     }\n");
      out.write("     \n");
      out.write("     function news_copy(text){\n");
      out.write("\t\t    if(text.indexOf('-') !== -1) {\n");
      out.write("\t\t        let arr = text.split('-');\n");
      out.write("\t\t        text = arr[0] + arr[1];\n");
      out.write("\t\t    }\n");
      out.write("\t\t    var textArea = document.createElement(\"textarea\");\n");
      out.write("\t\t      textArea.style.position = 'fixed';\n");
      out.write("\t\t      textArea.style.top = '0';\n");
      out.write("\t\t      textArea.style.left = '0';\n");
      out.write("\t\t      textArea.style.width = '2em';\n");
      out.write("\t\t      textArea.style.height = '2em';\n");
      out.write("\t\t      textArea.style.padding = '0';\n");
      out.write("\t\t      textArea.style.border = 'none';\n");
      out.write("\t\t      textArea.style.outline = 'none';\n");
      out.write("\t\t      textArea.style.boxShadow = 'none';\n");
      out.write("\t\t      textArea.style.background = 'transparent';\n");
      out.write("\t\t      textArea.value = text;\n");
      out.write("\t\t      document.body.appendChild(textArea);\n");
      out.write("\t\t      textArea.select();\n");
      out.write("\n");
      out.write("\t\t      try {\n");
      out.write("\t\t        var successful = document.execCommand('copy');\n");
      out.write("\t\t        var msg = successful ? '成功复制到剪贴板' : '该浏览器不支持点击复制到剪贴板';\n");
      out.write("\t\t       alert(msg);\n");
      out.write("\t\t      } catch (err) {\n");
      out.write("\t\t        alert('该浏览器不支持点击复制到剪贴板');\n");
      out.write("\t\t      }\n");
      out.write("\n");
      out.write("\t\t      document.body.removeChild(textArea);\n");
      out.write("  \t}\n");
      out.write("\n");
      out.write("   </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/data_news.jsp(253,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("entity");
      // /WEB-INF/view/data_news.jsp(253,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/data_news.jsp(253,18) '${news}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${news}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                    <tr>\n");
            out.write("                      <!--\n");
            out.write("                      <td>\n");
            out.write("                        <input type=\"checkbox\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                      </td>\n");
            out.write("                    -->\n");
            out.write("                      <td class=\"table-id\">\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                      </td>\n");
            out.write("                      <td class=\"table-title\">\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                      </td>\n");
            out.write("                      <!--\n");
            out.write("                      <td class=\"table-content\">\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getContent()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                      </td>\n");
            out.write("                    -->\n");
            out.write("                      <td class=\"table-time\">\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getTime()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                      </td>\n");
            out.write("                      <td class=\"table-url\">\n");
            out.write("                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getUrl()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\n");
            out.write("                      </td>\n");
            out.write("                      <td>\n");
            out.write("                        <div class=\"am-btn-toolbar\">\n");
            out.write("                          <div class=\"am-btn-group am-btn-group-xs\">\n");
            out.write("                            <button type=\"button\" class=\"am-btn am-btn-default am-btn-xs am-text-secondary\" onclick='news_select(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\")'><span class=\"am-icon-file\"></span> 查看</button>\n");
            out.write("                            <button class=\"am-btn am-btn-default am-btn-xs am-hide-sm-only\" onclick='news_copy(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\")'><span class=\"am-icon-copy\"></span> 复制</button>\n");
            out.write("                            <button class=\"am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only\" onclick='news_del(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entity.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\")'><span class=\"am-icon-trash-o\"></span> 删除</button>\n");
            out.write("                          </div>\n");
            out.write("                        </div>\n");
            out.write("                      </td>\n");
            out.write("                    </tr>\n");
            out.write("                  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
