/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2018-05-07 06:42:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class included_005fsidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"no-js fixed-layout\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  \n");
      out.write("    <div class=\"admin-sidebar am-offcanvas\" id=\"admin-offcanvas\">\n");
      out.write("      <div class=\"am-offcanvas-bar admin-offcanvas-bar\">\n");
      out.write("        <ul class=\"am-list admin-sidebar-list\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/index\">\n");
      out.write("              <span class=\"am-icon-home\"></span> 首 页\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("          <!--\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-nav'}\"><span class=\"am-icon-file\"></span> 页面模块 <span class=\"am-icon-angle-right am-fr am-margin-right\"></span></a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-nav\">\n");
      out.write("              <li><a href=\"admin-user.html\" class=\"am-cf\"><span class=\"am-icon-check\"></span> 个人资料<span class=\"am-icon-star am-fr am-margin-right admin-icon-yellow\"></span></a></li>\n");
      out.write("              <li><a href=\"admin-help.html\"><span class=\"am-icon-puzzle-piece\"></span> 帮助页</a></li>\n");
      out.write("              <li><a href=\"admin-gallery.html\"><span class=\"am-icon-th\"></span> 相册页面<span class=\"am-badge am-badge-secondary am-margin-right am-fr\">24</span></a></li>\n");
      out.write("              <li><a href=\"admin-log.html\"><span class=\"am-icon-calendar\"></span> 系统日志</a></li>\n");
      out.write("              <li><a href=\"admin-404.html\"><span class=\"am-icon-bug\"></span> 404</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          -->\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-spider'}\">\n");
      out.write("              <span class=\"am-icon-bug\"></span> 爬虫管理\n");
      out.write("              <span class=\"am-icon-angle-right am-fr am-margin-right\"></span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-spider\">\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/spider/check\" class=\"am-cf\">\n");
      out.write("                  <span class=\"am-icon-bug\"></span> 系统级爬虫\n");
      out.write("                  <span class=\"am-icon-star am-fr am-margin-right admin-icon-yellow\"></span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <!-- \n");
      out.write("              <li>\n");
      out.write("                <a href=\"#\">\n");
      out.write("                  <span class=\"am-icon-bug\"></span> 用户级爬虫</a>\n");
      out.write("                </li>\n");
      out.write("                -->\n");
      out.write("                <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memory/index\">\n");
      out.write("                  <span class=\"am-icon-area-chart\"></span> 性能监测</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-database'}\">\n");
      out.write("              <span class=\"am-icon-database\"></span> 原始数据\n");
      out.write("              <span class=\"am-icon-angle-right am-fr am-margin-right\"></span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-database\">\n");
      out.write("\t            <li>\n");
      out.write("\t                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/news/show\">\n");
      out.write("\t                  <span class=\"am-icon-pencil-square-o\"></span> 新闻表\n");
      out.write("\t                </a>\n");
      out.write("\t              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/show\">\n");
      out.write("                  <span class=\"am-icon-pencil-square-o\"></span> 公告表\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("                          \n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          \n");
      out.write("          <li>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newsDataAnalysis/index\">\n");
      out.write("              <span class=\"am-icon-pie-chart\"></span> 数据总览\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"admin-parent\">\n");
      out.write("            <a class=\"am-cf\" data-am-collapse=\"{target: '#collapse-data_operate'}\">\n");
      out.write("              <span class=\"am-icon-table\"></span> 数据处理\n");
      out.write("              <span class=\"am-icon-angle-right am-fr am-margin-right\"></span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"am-list am-collapse admin-sidebar-sub am-in\" id=\"collapse-data_operate\">\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newsDataProcess/index_pre\">\n");
      out.write("                  <span class=\"am-icon-pencil-square-o\"></span> 数据预处理\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newsDataProcess/index_wordSegment\">\n");
      out.write("                  <span class=\"am-icon-pie-chart\"></span> 分词与词频统计\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          \n");
      out.write("          <li>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/log/index\">\n");
      out.write("              <span class=\"am-icon-calendar\"></span> 系统日志\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <div class=\"am-panel am-panel-default admin-sidebar-panel\">\n");
      out.write("          <div class=\"am-panel-bd\">\n");
      out.write("            <p>\n");
      out.write("              <span class=\"am-icon-bookmark\"></span> 公 告\n");
      out.write("            </p>\n");
      out.write("            <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.getText()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"am-panel am-panel-default admin-sidebar-panel\">\n");
      out.write("          <div class=\"am-panel-bd\">\n");
      out.write("            <p>\n");
      out.write("              <span class=\"am-icon-tag\"></span>SpiderSystem\n");
      out.write("            </p>\n");
      out.write("            <p>Welcome to the SpiderSystem !</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <ul class=\"am-list admin-sidebar-list\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <span class=\"am-icon-sign-out\"></span> 注 销\n");
      out.write("            </a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
